spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sofia_code
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    jwt:
      token:
        header: Authorization
        secret: 123

